server:
  port: 8090

# Common Kafka Properties
auto:
  create:
    topics:
      enable: true

spring:

  # Consumer properties
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      group-id: group_id
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: group_id
      properties:
        spring:
          json:
            trusted:
              packages: "*"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_example
    username: postgres
    password: 123
    initialization-mode: never
    continue-on-error: false
  jpa:
    show-sql: true
    generate-ddl: false
  h2:
    console:
      enabled: true

# User's variables
topic:
  name:
    producer: topic.comand.test

logging:
  level:
    com:
      zaxxer:
        hikari: DEBUG
